CREATE OR REPLACE FUNCTION F_GENERAR_FACTURA 
(
  P_IDVENTA IN NUMBER 
, P_IDCLIENTE IN NUMBER 
, P_IDREPVENTAS IN NUMBER 
) RETURN VARCHAR2 AS 

    CURSOR c_venta is SELECT * FROM VENTA WHERE IDVENTA = P_IDVENTA;
    CURSOR c_cliente is SELECT * FROM PERSONA WHERE P_IDCLIENTE = IDPERSONA;
    CURSOR c_repventas is SELECT * FROM PERSONA WHERE P_IDCLIENTE = IDPERSONA;
    CURSOR c_detalle is SELECT * FROM DETALLEVENTA WHERE P_IDVENTA = IDVENTA;
BEGIN
    
    FOR l_detalle IN c_detalle LOOP
        NULL;    
    END LOOP;
    

  RETURN NULL;
END F_GENERAR_FACTURA;