/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 03-jun.-2018 10:03:08 p. m. 				*/
/*  DBMS       : Oracle 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "AUDITORIA" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

/* Create Tables */

CREATE TABLE  "AUDITORIA"
(
	"IDAUDITORIA" NUMBER(4) NOT NULL,    -- Este valor almacena el ID de la auditoría, además es la Primary Key de la tabla auditoría.
	"TABLAMODIFICADA" VARCHAR2(20) NOT NULL,    -- Esta variable se refiere al nombre de la tabla en la cual se realizó el cambio.  Las tablas a las cuales se les realiza la auditoría son: 	- CALIFICACIONVENTA 	- HISTORICOCRV 	- HISTORICOTIPOREP 	- VENTA
	"IDREGISTROMODIFICADO" NUMBER(4) NOT NULL,    -- Esta variable se refiere al identificador (Primary Key) del registro modificado.
	"VARIABLEMODIFICADA" VARCHAR2(20) NOT NULL,    -- Se refiere al identificador de la variable a la cual se realizó la modificación, por ejemplo CALIFICACION en la tabla HISTORICOTIPOREP.
	"VALORANTIGUO" VARCHAR2(20) NOT NULL,    -- Almacena el valor antiguo de la variable modificada para mantener el registro del cambio.
	"VALORNUEVO" VARCHAR2(20) NOT NULL,    -- Almacena el nuevo valor de la variable modificada.
	"USUARIOMODIFICADOR" VARCHAR2(30) NOT NULL,    -- Esta variable almacena el identificador del usuario que realizó la modificación en la tabla, por ejemplo el usuario F1005855668, quien es el administrador de la BD
	"FECHAMODIFICACION" DATE NOT NULL    -- Esta variable almacena la fecha y la hora en la cual se realizaron las modificaciones, para así lograr el seguimiento de los cambios realizados en la BD.
)
;

/* Create Comments, Sequences and Triggers for Autonumber Columns */

COMMENT ON TABLE  "AUDITORIA" IS 'Tabla encargada de almacenar el registro de cada cambio realizado sobre las tablas (CalificacionVentaa,HistoricoCRV,HistoricoTipoRep,Venta) en la Base de Datos Almacena los siguientes datos:  	- Id de la Auditoria 	- Tabla auditada 	- Id del registro auditado 	- Variable auditada 	- Valor antiguo de la variable auditada 	- Nuevo Valor de la variable auditada 	- Usuario que realizo el cambio 	- Fecha en la cual se realizó el cambio'
;

COMMENT ON COLUMN  "AUDITORIA"."IDAUDITORIA" IS 'Este valor almacena el ID de la auditoría, además es la Primary Key de la tabla auditoría.'
;

COMMENT ON COLUMN  "AUDITORIA"."TABLAMODIFICADA" IS 'Esta variable se refiere al nombre de la tabla en la cual se realizó el cambio.  Las tablas a las cuales se les realiza la auditoría son: 	- CALIFICACIONVENTA 	- HISTORICOCRV 	- HISTORICOTIPOREP 	- VENTA'
;

COMMENT ON COLUMN  "AUDITORIA"."IDREGISTROMODIFICADO" IS 'Esta variable se refiere al identificador (Primary Key) del registro modificado.'
;

COMMENT ON COLUMN  "AUDITORIA"."VARIABLEMODIFICADA" IS 'Se refiere al identificador de la variable a la cual se realizó la modificación, por ejemplo CALIFICACION en la tabla HISTORICOTIPOREP.'
;

COMMENT ON COLUMN  "AUDITORIA"."VALORANTIGUO" IS 'Almacena el valor antiguo de la variable modificada para mantener el registro del cambio.'
;

COMMENT ON COLUMN  "AUDITORIA"."VALORNUEVO" IS 'Almacena el nuevo valor de la variable modificada.'
;

COMMENT ON COLUMN  "AUDITORIA"."USUARIOMODIFICADOR" IS 'Esta variable almacena el identificador del usuario que realizó la modificación en la tabla, por ejemplo el usuario F1005855668, quien es el administrador de la BD'
;

COMMENT ON COLUMN  "AUDITORIA"."FECHAMODIFICACION" IS 'Esta variable almacena la fecha y la hora en la cual se realizaron las modificaciones, para así lograr el seguimiento de los cambios realizados en la BD.'
;

/* Create Primary Keys, Indexes, Uniques, Checks, Triggers */

ALTER TABLE  "AUDITORIA" 
 ADD CONSTRAINT "PK_AUDITORIA"
	PRIMARY KEY ("IDAUDITORIA") 
 USING INDEX
;
