drop user multinivel cascade;
drop user s1018485092 cascade;
drop user a1005855865 cascade;
drop user j1016091072 cascade;
drop user p1023944061 cascade;
drop user j1018492522 cascade;


drop tablespace DEFMULTINIVEL;
drop tablespace DEFRMUNDO;
drop tablespace TEMRMULTINIVEL;


drop role R_MULTINIVEL;
drop role R_CLIENTE;
drop role R_REPRESENTANTEVENTAS;

DROP PUBLIC SYNONYM BANK;
DROP PUBLIC SYNONYM QUALIFICATION;
DROP PUBLIC SYNONYM JOB;
DROP PUBLIC SYNONYM CATEGORY;
DROP PUBLIC SYNONYM CITY;
DROP PUBLIC SYNONYM CONTACT;
DROP PUBLIC SYNONYM DETAILPAYMENT;
DROP PUBLIC SYNONYM DETAILSALE;
DROP PUBLIC SYNONYM STATESALE;
DROP PUBLIC SYNONYM ITEM;
DROP PUBLIC SYNONYM COUNTRY;
DROP PUBLIC SYNONYM PERSON;
DROP PUBLIC SYNONYM PRODUCT;
DROP PUBLIC SYNONYM REGION;
DROP PUBLIC SYNONYM INVENTARIO;
DROP PUBLIC SYNONYM SUBCATEGORY;
DROP PUBLIC SYNONYM CARD;
DROP PUBLIC SYNONYM TYPECONTACT;
DROP PUBLIC SYNONYM TYPEPAYMENT;
DROP PUBLIC SYNONYM TYPEAGENTSALES;
DROP PUBLIC SYNONYM SALE;
