-- Ejecutar desde System

-- Schema Multinivel 

CREATE USER MULTINIVEL identified by finalbases DEFAULT TABLESPACE DEFMULTINIVEL TEMPORARY TABLESPACE TEMRMULTINIVEL QUOTA 10M ON DEFMULTINIVEL;

-- Role para Multinivel 

CREATE ROLE R_MULTINIVEL;

-- Asignación de permisos

GRANT CONNECT, CREATE TABLE, CREATE SEQUENCE, CREATE VIEW, CREATE PROCEDURE,CREATE ANY DIRECTORY, CREATE PUBLIC SYNONYM TO R_MULTINIVEL;

-- Asignación del ROLE a MULINIVEL

GRANT R_MULTINIVEL TO MULTINIVEL;


