--Role Administrador

CREATE ROLE R_ADMINISTRADOR;

GRANT CONNECT, CREATE ROLE, TO R_ADMINISTRADOR;

GRANT SELECT CATEGORY TO R_ADMINISTRADOR;
GRANT SELECT PRODUCT TO R_ADMINISTRADOR;
GRANT SELECT DETAILSALE TO R_ADMINISTRADOR;
GRANT SELECT COUNTRY TO R_ADMINISTRADOR;
GRANT SELECT ZONE TO R_ADMINISTRADOR;
GRANT SELECT CITY TO R_ADMINISTRADOR;
GRANT SELECT ARTICLE TO R_ADMINISTRADOR;
GRANT SELECT SALE TO R_ADMINISTRADOR;
GRANT SELECT SALEQUALIFICATION TO R_ADMINISTRADOR;
GRANT SELECT DETAILPAYMENT TO R_ADMINISTRADOR;
GRANT SELECT PERSON TO R_ADMINISTRADOR;
GRANT SELECT CLIENT TO R_ADMINISTRADOR;
GRANT SELECT BANK TO R_ADMINISTRADOR;
GRANT SELECT CARD TO R_ADMINISTRADOR;
GRANT SELECT QUALIFICATION TO R_ADMINISTRADOR;
GRANT SELECT AGENTSALES TO R_ADMINISTRADOR;
GRANT SELECT HISTORICALTYPEAGENT TO R_ADMINISTRADOR;
GRANT SELECT HISTORICALCRV TO R_ADMINISTRADOR 
GRANT SELECT CONTACT TO R_ADMINISTRADOR;
GRANT SELECT TYPECONTACT TO R_ADMINISTRADOR;
GRANT SELECT TYPEAGENTSALES TO R_ADMINISTRADOR;


GRANT SELECT ON MULTINIVEL.ARTICULO TO R_ADMINISTRADOR;

GRANT INSERT ON SALE TO R_ADMINISTRADOR;
GRANT INSERT ON DETAILSALE TO R_ADMINISTRADOR;
GRANT INSERT ON DETAILPAYMENT TO R_ADMINISTRADOR;
GRANT INSERT ON HISTORICALCRV TO R_ADMINISTRADOR;

GRANT INSERT (PUNTAJECALIFICACION, COMENTARIO) ON QUALIFICATION TO R_ADMINISTRADOR;
GRANT INSERT (CALIFICACION, DETALLECALIFICACION) ON SALEQUALIFICATION TO R_ADMINISTRADOR;
GRANT UPDATE (ULTIMACONEXION) ON PERSON TO R_ADMINISTRADOR;
GRANT UPDATE ON ARTICLE TO R_ADMINISTRADOR;


GRANT SELECT ON MULTINIVEL.SEQ_VENTA_IDVENTA TO R_ADMINISTRADOR;
GRANT SELECT ON MULTINIVEL.SEQ_DETALLEVENTA_ID TO R_ADMINISTRADOR;
GRANT SELECT ON MULTINIVEL.SEQ_DETALLEPAGO_IDDETALLEPAGO TO R_ADMINISTRADOR;
GRANT SELECT ON MULTINIVEL.SEQ_ITEM_IDITEM TO R_ADMINISTRADOR;
GRANT SELECT ON MULTINIVEL.SEQ_HISTORICOCRV_ID TO R_ADMINISTRADOR;

GRANT INSERT ON PERSON TO R_ADMINISTRADOR;
GRANT INSERT ON CLIENT TO R_ADMINISTRADOR;
GRANT UPDATE ON PERSON TO R_ADMINISTRADOR;
GRANT UPDATE ON CLIENT TO R_ADMINISTRADOR;
GRANT INSERT ON CONTACT TO R_ADMINISTRADOR;

GRANT SELECT ON MULTINIVEL.ARTICULO TO R_ADMINISTRADOR;

GRANT SELECT ON MULTINIVEL.SEQ_CONTACTO_IDCONTACTO TO R_ADMINISTRADOR;


-- Role Cliente 

CREATE ROLE R_CLIENTE;

GRANT CONNECT TO R_CLIENTE;

GRANT SELECT CATEGORY TO R_CLIENTE;
GRANT SELECT PRODUCT TO R_CLIENTE;
GRANT SELECT ARTICLE TO R_CLIENTE;
GRANT SELECT COUNTRY TO R_CLIENTE;
GRANT SELECT ZONE TO R_CLIENTE;
GRANT SELECT CITY TO R_CLIENTE;
GRANT SELECT BANK TO R_CLIENTE;
GRANT SELECT CARD TO R_CLIENTE;
GRANT SELECT SALE TO R_CLIENTE;
GRANT SELECT DETAILSALE TO R_CLIENTE;
GRANT SELECT SALEQUALIFICATION TO R_CLIENTE;
GRANT SELECT DETAILPAYMENT TO R_CLIENTE;
GRANT SELECT HISTORICALCRV TO R_CLIENTE

GRANT SELECT ON MULTINIVEL.ARTICULO TO R_CLIENTE;

GRANT INSERT ON SALE TO R_CLIENTE;
GRANT INSERT ON DETAILSALE TO R_CLIENTE;
GRANT INSERT ON DETAILPAYMENT TO R_CLIENTE;
GRANT INSERT ON HISTORICALCRV TO R_CLIENTE;

GRANT INSERT (PUNTAJECALIFICACION, COMENTARIO) ON QUALIFICATION TO R_CLIENTE;
GRANT INSERT (CALIFICACION, DETALLECALIFICACION) ON SALEQUALIFICATION TO R_CLIENTE;
GRANT UPDATE (ULTIMACONEXION) ON PERSON TO R_CLIENTE;
GRANT UPDATE ON ARTICLE TO R_CLIENTE;

-- GRANT R_CLIENTE TO USER_CLIENTE->Script asignacion cliente desde la aplicación 

-- SECUENCIAS IMPORTANTE DEFINIR PERMISOS DE LAS SECUENCIAS QUE EL CLIENTE PUEDE UTILIZAR

GRANT SELECT ON MULTINIVEL.SEQ_VENTA_IDVENTA TO R_CLIENTE;
GRANT SELECT ON MULTINIVEL.SEQ_DETALLEVENTA_ID TO R_CLIENTE;
GRANT SELECT ON MULTINIVEL.SEQ_DETALLEPAGO_IDDETALLEPAGO TO R_CLIENTE;
GRANT SELECT ON MULTINIVEL.SEQ_ITEM_IDITEM TO R_CLIENTE;
GRANT SELECT ON MULTINIVEL.SEQ_HISTORICOCRV_ID TO R_CLIENTE 


-- Role Representante de Ventas 

CREATE ROLE R_REPRESENTANTEVENTAS;

GRANT CONNECT, CREATE USER TO R_REPRESENTANTEVENTAS;
GRANT R_CLIENTE TO R_REPRESENTANTEVENTAS WITH ADMIN OPTION;


GRANT SELECT COUNTRY TO R_REPRESENTANTEVENTAS;
GRANT SELECT ZONE TO R_REPRESENTANTEVENTAS;
GRANT SELECT CITY TO R_REPRESENTANTEVENTAS;
GRANT SELECT SALE TO R_REPRESENTANTEVENTAS;
GRANT SELECT SALEQUALIFICATION TOR_REPRESENTANTEVENTAS;
GRANT SELECT QUALIFICATION TO R_REPRESENTANTEVENTAS;
GRANT SELECT HISTORICALTYPEAGENT TO R_REPRESENTANTEVENTAS;
GRANT SELECT HISTORICALCRV TO R_REPRESENTANTEVENTAS;
GRANT SELECT CONTACT TO R_REPRESENTANTEVENTAS;
GRANT SELECT TYPECONTACT TO R_REPRESENTANTEVENTAS;
GRANT SELECT TYPEAGENTSALES TO R_REPRESENTANTEVENTAS;

GRANT INSERT ON PERSON TO R_REPRESENTANTEVENTAS;
GRANT INSERT ON CLIENT TO R_REPRESENTANTEVENTAS;
GRANT UPDATE ON PERSON TO R_REPRESENTANTEVENTAS;
GRANT UPDATE ON CLIENT TO R_REPRESENTANTEVENTAS;
GRANT INSERT ON CONTACT TO R_REPRESENTANTEVENTAS;

GRANT SELECT ON MULTINIVEL.ARTICULO TO R_REPRESENTANTEVENTAS;

-- SECUENCIAS IMPORTANTE DEFINIR PERMISOS DE LAS SECUENCIAS QUE EL RV PUEDE UTILIZAR

GRANT SELECT ON MULTINIVEL.SEQ_CONTACTO_IDCONTACTO TO R_REPRESENTANTEVENTAS;


-- GRANT R_REPRESENTANTEVENTAS TO USER_REPRESENTANTEVENTAS 

GRANT R_REPRESENTANTEVENTAS TO s1018485092;
GRANT R_REPRESENTANTEVENTAS TO a1005855865;
GRANT R_REPRESENTANTEVENTAS TO j1016091072;
GRANT R_REPRESENTANTEVENTAS TO p1023944061;
GRANT R_REPRESENTANTEVENTAS TO j1018492522;

