-- Ejecutar desde f1005855668

-- Role Cliente 

CREATE ROLE R_CLIENTE;

GRANT CONNECT, CREATE SESSION TO R_CLIENTE;

GRANT SELECT ON CATEGORY TO R_CLIENTE;
GRANT SELECT ON PRODUCT TO R_CLIENTE;
GRANT SELECT ON ARTICLE TO R_CLIENTE;
GRANT SELECT ON COUNTRY TO R_CLIENTE;
GRANT SELECT ON ZONE TO R_CLIENTE;
GRANT SELECT ON CITY TO R_CLIENTE;
GRANT SELECT ON BANK TO R_CLIENTE;
GRANT SELECT ON CARD TO R_CLIENTE;
GRANT SELECT ON SALE TO R_CLIENTE;
GRANT SELECT ON DETAILSALE TO R_CLIENTE;
GRANT SELECT ON SALEQUALIFICATION TO R_CLIENTE;
GRANT SELECT ON DETAILPAYMENT TO R_CLIENTE;
GRANT SELECT ON HISTORICALCRV TO R_CLIENTE;
GRANT SELECT ON PERSON TO R_CLIENTE;
GRANT SELECT ON CLIENT TO R_CLIENTE;
GRANT SELECT ON AGENTSALES TO R_CLIENTE;

GRANT SELECT ON OBJECT TO R_CLIENTE;

GRANT INSERT ON SALE TO R_CLIENTE;
GRANT INSERT ON DETAILSALE TO R_CLIENTE;
GRANT INSERT ON DETAILPAYMENT TO R_CLIENTE;
GRANT INSERT ON HISTORICALCRV TO R_CLIENTE;

GRANT INSERT (CALIFICACION, DETALLECALIFICACION) ON SALEQUALIFICATION TO R_CLIENTE;
GRANT UPDATE (ULTIMACONEXION) ON PERSON TO R_CLIENTE;
GRANT UPDATE ON ARTICLE TO R_CLIENTE;

-- GRANT R_CLIENTE TO USER_CLIENTE->Script asignacion cliente desde la aplicación 

-- SECUENCIAS, IMPORTANTE DEFINIR PERMISOS DE LAS SECUENCIAS QUE EL CLIENTE PUEDE UTILIZAR

GRANT SELECT ON MULTINIVEL.SEQ_VENTA_IDVENTA TO R_CLIENTE;
GRANT SELECT ON MULTINIVEL.SEQ_DETALLEVENTA_ID TO R_CLIENTE;
GRANT SELECT ON MULTINIVEL.SEQ_DETALLEPAGO_IDDETALLEPAGO TO R_CLIENTE;
GRANT SELECT ON MULTINIVEL.SEQ_ITEM_IDITEM TO R_CLIENTE;
GRANT SELECT ON MULTINIVEL.SEQ_HISTORICOCRV_ID TO R_CLIENTE;
GRANT SELECT ON MULTINIVEL.SEQ_CALIFICACIONVENTA_ID TO R_CLIENTE;

GRANT EXECUTE ON MULTINIVEL.FN_GENERAR_FACTURA TO R_CLIENTE;

-- Role Representante de Ventas 

CREATE ROLE R_REPRESENTANTEVENTAS;

GRANT CONNECT, CREATE SESSION, CREATE USER TO R_REPRESENTANTEVENTAS;
GRANT R_CLIENTE TO R_REPRESENTANTEVENTAS WITH ADMIN OPTION;


GRANT SELECT ON COUNTRY TO R_REPRESENTANTEVENTAS;
GRANT SELECT ON ZONE TO R_REPRESENTANTEVENTAS;
GRANT SELECT ON CITY TO R_REPRESENTANTEVENTAS;
GRANT SELECT ON SALE TO R_REPRESENTANTEVENTAS;
GRANT SELECT ON SALEQUALIFICATION TO R_REPRESENTANTEVENTAS;
GRANT SELECT ON HISTORICALTYPEAGENT TO R_REPRESENTANTEVENTAS;
GRANT SELECT ON HISTORICALCRV TO R_REPRESENTANTEVENTAS;
GRANT SELECT ON CONTACT TO R_REPRESENTANTEVENTAS;
GRANT SELECT ON TYPECONTACT TO R_REPRESENTANTEVENTAS;
GRANT SELECT ON TYPEAGENTSALES TO R_REPRESENTANTEVENTAS;
GRANT SELECT ON PERSON TO R_REPRESENTANTEVENTAS;
GRANT SELECT ON AGENTSALES TO R_REPRESENTANTEVENTAS;


GRANT INSERT ON PERSON TO R_REPRESENTANTEVENTAS;
GRANT INSERT ON CLIENT TO R_REPRESENTANTEVENTAS;
GRANT UPDATE ON PERSON TO R_REPRESENTANTEVENTAS;
GRANT UPDATE ON CLIENT TO R_REPRESENTANTEVENTAS;
GRANT INSERT ON CONTACT TO R_REPRESENTANTEVENTAS;
GRANT INSERT ON HISTORICALCRV TO R_REPRESENTANTEVENTAS;

--GRANT SELECT ON MULTINIVEL.ARTICULO TO R_REPRESENTANTEVENTAS;

-- SECUENCIAS IMPORTANTE DEFINIR PERMISOS DE LAS SECUENCIAS QUE EL RV PUEDE UTILIZAR

GRANT SELECT ON MULTINIVEL.SEQ_CONTACTO_IDCONTACTO TO R_REPRESENTANTEVENTAS;
GRANT SELECT ON MULTINIVEL.SEQ_HISTORICOCRV_ID TO R_REPRESENTANTEVENTAS;



-- GRANT R_REPRESENTANTEVENTAS TO USER_REPRESENTANTEVENTAS 

GRANT R_REPRESENTANTEVENTAS TO s1018485092;
GRANT R_REPRESENTANTEVENTAS TO a1005855865;
GRANT R_REPRESENTANTEVENTAS TO j1016091072;
GRANT R_REPRESENTANTEVENTAS TO p1023944061;
GRANT R_REPRESENTANTEVENTAS TO j1018492522;

