
/*Creació schema Multinivel */
CREATE USER MULTINIVEL identified by finalbases DEFAULT TABLESPACE DEFMULTINIVEL TEMPORARY TABLESPACE TEMRMULTINIVEL QUOTA 10M ON DEFMULTINIVEL;

/* Creacion schemas de Representantes de ventas */

CREATE USER s1018485092 identified by finalbases DEFAULT TABLESPACE DEFRMUNDO TEMPORARY TABLESPACE TEMRMULTINIVEL;

CREATE USER a1005855865 identified by finalbases DEFAULT TABLESPACE DEFRMUNDO TEMPORARY TABLESPACE TEMRMULTINIVEL;

CREATE USER j1016091072 identified by finalbases DEFAULT TABLESPACE DEFRMUNDO TEMPORARY TABLESPACE TEMRMULTINIVEL;

CREATE USER p1023944061 identified by finalbases DEFAULT TABLESPACE DEFRMUNDO TEMPORARY TABLESPACE TEMRMULTINIVEL;

CREATE USER j1018492522 identified by finalbases DEFAULT TABLESPACE DEFRMUNDO TEMPORARY TABLESPACE TEMRMULTINIVEL; 
