-- Sinonimos, crear desde Multinivel

CREATE PUBLIC SYNONYM BANK FOR MULTINIVEL.BANCO;
CREATE PUBLIC SYNONYM QUALIFICATION FOR MULTINIVEL.CALIFICACION;
CREATE PUBLIC SYNONYM JOB FOR MULTINIVEL.CARGO;
CREATE PUBLIC SYNONYM CATEGORY FOR MULTINIVEL.CATEGORIA;
CREATE PUBLIC SYNONYM CITY FOR MULTINIVEL.CIUDAD;
CREATE PUBLIC SYNONYM CONTACT FOR MULTINIVEL.CONTACTO;
CREATE PUBLIC SYNONYM DETAILPAYMENT FOR MULTINIVEL.DETALLEPAGO;
CREATE PUBLIC SYNONYM DETAILSALE FOR MULTINIVEL.DETALLEVENTA;
CREATE PUBLIC SYNONYM STATESALE FOR MULTINIVEL.ESTADOVENTA;
CREATE PUBLIC SYNONYM ITEM FOR MULTINIVEL.ITEM;
CREATE PUBLIC SYNONYM COUNTRY FOR MULTINIVEL.PAIS;
CREATE PUBLIC SYNONYM PERSON FOR MULTINIVEL.PERSONA;
CREATE PUBLIC SYNONYM PRODUCT FOR MULTINIVEL.PRODUCTO;
CREATE PUBLIC SYNONYM REGION FOR MULTINIVEL.REGION;
CREATE PUBLIC SYNONYM INVENTARIO FOR MULTINIVEL.STOCK;
CREATE PUBLIC SYNONYM SUBCATEGORY FOR MULTINIVEL.SUBCATEGORIA;
CREATE PUBLIC SYNONYM CARD FOR MULTINIVEL.TARJETA;
CREATE PUBLIC SYNONYM TYPECONTACT FOR MULTINIVEL.TIPOCONTACTO;
CREATE PUBLIC SYNONYM TYPEPAYMENT FOR MULTINIVEL.TIPOPAGO;
CREATE PUBLIC SYNONYM TYPEAGENTSALES FOR MULTINIVEL.TIPOREPRESENTANTEVENTAS;
CREATE PUBLIC SYNONYM SALE FOR MULTINIVEL.VENTA;
