-- Sinonimos, crear desde Multinivel

CREATE PUBLIC SYNONYM CATEGORY FOR MULTINIVEL.CATEGORIA;
CREATE PUBLIC SYNONYM PRODUCT FOR MULTINIVEL.PRODUCTO;
CREATE PUBLIC SYNONYM DETAILSALE FOR MULTINIVEL.DETALLEVENTA;
CREATE PUBLIC SYNONYM COUNTRY FOR MULTINIVEL.PAIS;
CREATE PUBLIC SYNONYM ZONE FOR MULTINIVEL.REGION;
CREATE PUBLIC SYNONYM CITY FOR MULTINIVEL.CIUDAD;
CREATE PUBLIC SYNONYM ARTICLE FOR MULTINIVEL.ITEM;
CREATE PUBLIC SYNONYM SALE FOR MULTINIVEL.VENTA;
CREATE PUBLIC SYNONYM SALEQUALIFICATION FOR MULTINIVEL.CALIFICACIONVENTA;
CREATE PUBLIC SYNONYM DETAILPAYMENT FOR MULTINIVEL.DETALLEPAGO;
CREATE PUBLIC SYNONYM PERSON FOR MULTINIVEL.PERSONA;
CREATE PUBLIC SYNONYM CLIENT FOR MULTINIVEL.CLIENTE;
CREATE PUBLIC SYNONYM BANK FOR MULTINIVEL.BANCO;
CREATE PUBLIC SYNONYM CARD FOR MULTINIVEL.TARJETA;
CREATE PUBLIC SYNONYM AGENTSALES FOR MULTINIVEL.REPRESENTANTEVENTAS;
CREATE PUBLIC SYNONYM HISTORICALTYPEAGENT FOR MULTINIVEL.HISTORICOTIPOREP;
CREATE PUBLIC SYNONYM HISTORICALCRV  FOR MULTINIVEL.HISTORICOCRV;
CREATE PUBLIC SYNONYM CONTACT FOR MULTINIVEL.CONTACTO;
CREATE PUBLIC SYNONYM TYPECONTACT FOR MULTINIVEL.TIPOCONTACTO;
CREATE PUBLIC SYNONYM TYPEAGENTSALES FOR MULTINIVEL.TIPOREPRESENTANTEVENTAS;
CREATE PUBLIC SYNONYM OBJECT FOR MULTINIVEL.ARTICULO;
CREATE PUBLIC SYNONYM VARS FOR MULTINIVEL.VARIABLES;
CREATE PUBLIC SYNONYM HISTORICALVARS FOR MULTINIVEL.HISTORICOVARIABLES;
CREATE PUBLIC SYNONYM AUDIT FOR MULTINIVEL.AUDITORIA;
