
/* Creación TABLESPACES DEFAULT */

CREATE TABLESPACE DEFMULTINIVEL DATAFILE 'C:\oraclexe\app\oracle\oradata\XE\DEFMULTINIVEL.DBF' SIZE 20M AUTOEXTEND ON NEXT 10M MAXSIZE 100M;

CREATE TABLESPACE DEFRMUNDO DATAFILE 'C:\oraclexe\app\oracle\oradata\XE\DEFRMUNDO.DBF' SIZE 20M;

/*Creación TABLESPACE TEMPORARY */

CREATE TEMPORARY TABLESPACE TEMRMULTINIVEL1 TEMPFILE 'C:\oraclexe\app\oracle\oradata\XE\TEMRMULTINIVEL.DBF' SIZE 15M;

