start "C:\Users\Santiago\Documents\NetBeansProjects\FinalBases2\SCRIPT\Seguridad\Tablespace.sql";
start "C:\Users\Santiago\Documents\NetBeansProjects\FinalBases2\SCRIPT\Seguridad\Multinivel.sql";
conn multinivel/finalbases
start "C:\Users\Santiago\Documents\NetBeansProjects\FinalBases2\SCRIPT\ScriptModeloBD.sql";
start "C:\Users\Santiago\Documents\NetBeansProjects\FinalBases2\SCRIPT\ScriptLlenado.sql";
start "C:\Users\Santiago\Documents\NetBeansProjects\FinalBases2\SCRIPT\Seguridad\Vistas.sql";
start "C:\Users\Santiago\Documents\NetBeansProjects\FinalBases2\SCRIPT\Seguridad\Sinonimos.sql";
conn system/HESOYAMYASNAEB
start "C:\Users\Santiago\Documents\NetBeansProjects\FinalBases2\SCRIPT\Seguridad\Admin.sql";
conn f1005855668/finalbases
start "C:\Users\Santiago\Documents\NetBeansProjects\FinalBases2\SCRIPT\Seguridad\Schemas.sql";
start "C:\Users\Santiago\Documents\NetBeansProjects\FinalBases2\SCRIPT\Seguridad\Roles.sql";