drop user multinivel cascade;
drop user s1018485092 cascade;
drop user a1005855865 cascade;
drop user j1016091072 cascade;
drop user p1023944061 cascade;
drop user j1018492522 cascade;


drop tablespace DEFMULTINIVEL;
drop tablespace DEFRMUNDO;
drop tablespace TEMRMULTINIVEL;


drop role R_MULTINIVEL;
drop role R_CLIENTE;
drop role R_REPRESENTANTEVENTAS;


DROP PUBLIC SYNONYM CATEGORY;
DROP PUBLIC SYNONYM PRODUCT;
DROP PUBLIC SYNONYM DETAILSALE;
DROP PUBLIC SYNONYM COUNTRY;
DROP PUBLIC SYNONYM ZONE;
DROP PUBLIC SYNONYM CITY;
DROP PUBLIC SYNONYM ARTICLE;
DROP PUBLIC SYNONYM SALE;
DROP PUBLIC SYNONYM SALEQUALIFICATION;
DROP PUBLIC SYNONYM DETAILPAYMENT;
DROP PUBLIC SYNONYM PERSON;
DROP PUBLIC SYNONYM CLIENT;
DROP PUBLIC SYNONYM BANK;
DROP PUBLIC SYNONYM CARD;
DROP PUBLIC SYNONYM QUALIFICATION;
DROP PUBLIC SYNONYM AGENTSALES;
DROP PUBLIC SYNONYM HISTORICALTYPEAGENT;
DROP PUBLIC SYNONYM CONTACT;
DROP PUBLIC SYNONYM TYPECONTACT;
DROP PUBLIC SYNONYM TYPEAGENTSALES;
