INSERT INTO CATEGORIA(IDCATEGORIA,NOMBRECATEGORIA) VALUES(SEQ_CATEGORIA_IDCATEGORIA.NEXTVAL,'Nutricion');
INSERT INTO CATEGORIA(IDCATEGORIA,NOMBRECATEGORIA) VALUES(SEQ_CATEGORIA_IDCATEGORIA.NEXTVAL,'Belleza');
INSERT INTO CATEGORIA(IDCATEGORIA,NOMBRECATEGORIA) VALUES(SEQ_CATEGORIA_IDCATEGORIA.NEXTVAL,'Hogar');
INSERT INTO CATEGORIA(IDCATEGORIA,NOMBRECATEGORIA) VALUES(SEQ_CATEGORIA_IDCATEGORIA.NEXTVAL,'Cuidado Personal');