INSERT INTO CATEGORIA(IDCATEGORIA,NOMBRECATEGORIA,IDSUBCATEGORIA) VALUES(SEQ_CATEGORIA_IDCATEGORIA.NEXTVAL,'Nutricion',1);
INSERT INTO CATEGORIA(IDCATEGORIA,NOMBRECATEGORIA,IDSUBCATEGORIA) VALUES(SEQ_CATEGORIA_IDCATEGORIA.NEXTVAL,'Nutricion',2);
INSERT INTO CATEGORIA(IDCATEGORIA,NOMBRECATEGORIA,IDSUBCATEGORIA) VALUES(SEQ_CATEGORIA_IDCATEGORIA.NEXTVAL,'Nutricion',3);
INSERT INTO CATEGORIA(IDCATEGORIA,NOMBRECATEGORIA,IDSUBCATEGORIA) VALUES(SEQ_CATEGORIA_IDCATEGORIA.NEXTVAL,'Nutricion',4);
INSERT INTO CATEGORIA(IDCATEGORIA,NOMBRECATEGORIA,IDSUBCATEGORIA) VALUES(SEQ_CATEGORIA_IDCATEGORIA.NEXTVAL,'Nutricion',5);

INSERT INTO CATEGORIA(IDCATEGORIA,NOMBRECATEGORIA,IDSUBCATEGORIA) VALUES(SEQ_CATEGORIA_IDCATEGORIA.NEXTVAL,'Belleza',6);
INSERT INTO CATEGORIA(IDCATEGORIA,NOMBRECATEGORIA,IDSUBCATEGORIA) VALUES(SEQ_CATEGORIA_IDCATEGORIA.NEXTVAL,'Belleza',7);
INSERT INTO CATEGORIA(IDCATEGORIA,NOMBRECATEGORIA,IDSUBCATEGORIA) VALUES(SEQ_CATEGORIA_IDCATEGORIA.NEXTVAL,'Belleza',8);
INSERT INTO CATEGORIA(IDCATEGORIA,NOMBRECATEGORIA,IDSUBCATEGORIA) VALUES(SEQ_CATEGORIA_IDCATEGORIA.NEXTVAL,'Belleza',9);

INSERT INTO CATEGORIA(IDCATEGORIA,NOMBRECATEGORIA,IDSUBCATEGORIA) VALUES(SEQ_CATEGORIA_IDCATEGORIA.NEXTVAL,'Hogar',10);
INSERT INTO CATEGORIA(IDCATEGORIA,NOMBRECATEGORIA,IDSUBCATEGORIA) VALUES(SEQ_CATEGORIA_IDCATEGORIA.NEXTVAL,'Hogar',11);
INSERT INTO CATEGORIA(IDCATEGORIA,NOMBRECATEGORIA,IDSUBCATEGORIA) VALUES(SEQ_CATEGORIA_IDCATEGORIA.NEXTVAL,'Hogar',12);
INSERT INTO CATEGORIA(IDCATEGORIA,NOMBRECATEGORIA,IDSUBCATEGORIA) VALUES(SEQ_CATEGORIA_IDCATEGORIA.NEXTVAL,'Hogar',13);

INSERT INTO CATEGORIA(IDCATEGORIA,NOMBRECATEGORIA,IDSUBCATEGORIA) VALUES(SEQ_CATEGORIA_IDCATEGORIA.NEXTVAL,'Cuidado Personal',14);
INSERT INTO CATEGORIA(IDCATEGORIA,NOMBRECATEGORIA,IDSUBCATEGORIA) VALUES(SEQ_CATEGORIA_IDCATEGORIA.NEXTVAL,'Cuidado Personal',15);
INSERT INTO CATEGORIA(IDCATEGORIA,NOMBRECATEGORIA,IDSUBCATEGORIA) VALUES(SEQ_CATEGORIA_IDCATEGORIA.NEXTVAL,'Cuidado Personal',16);
INSERT INTO CATEGORIA(IDCATEGORIA,NOMBRECATEGORIA,IDSUBCATEGORIA) VALUES(SEQ_CATEGORIA_IDCATEGORIA.NEXTVAL,'Cuidado Personal',17);
INSERT INTO CATEGORIA(IDCATEGORIA,NOMBRECATEGORIA,IDSUBCATEGORIA) VALUES(SEQ_CATEGORIA_IDCATEGORIA.NEXTVAL,'Cuidado Personal',18);
INSERT INTO CATEGORIA(IDCATEGORIA,NOMBRECATEGORIA,IDSUBCATEGORIA) VALUES(SEQ_CATEGORIA_IDCATEGORIA.NEXTVAL,'Cuidado Personal',19);

