INSERT INTO ESTADOVENTA(IDESTADOVENTA,NOMBREESTADOVENTA) VALUES(SEQ_ESTADOVENTA_IDESTADOVENTA.NEXTVAL,'OK');
INSERT INTO ESTADOVENTA(IDESTADOVENTA,NOMBREESTADOVENTA) VALUES(SEQ_ESTADOVENTA_IDESTADOVENTA.NEXTVAL,'NO AUTORIZADO');
INSERT INTO ESTADOVENTA(IDESTADOVENTA,NOMBREESTADOVENTA) VALUES(SEQ_ESTADOVENTA_IDESTADOVENTA.NEXTVAL,'PENDIENTE');
INSERT INTO ESTADOVENTA(IDESTADOVENTA,NOMBREESTADOVENTA) VALUES(SEQ_ESTADOVENTA_IDESTADOVENTA.NEXTVAL,'FALLIDO');