
INSERT INTO PAIS(IDPAIS,NOMBREPAIS) VALUES (SEQ_PAIS_IDPAIS.NEXTVAL,'Colombia');
INSERT INTO PAIS(IDPAIS,NOMBREPAIS) VALUES (SEQ_PAIS_IDPAIS.NEXTVAL,'Ecuador');
INSERT INTO PAIS(IDPAIS,NOMBREPAIS) VALUES (SEQ_PAIS_IDPAIS.NEXTVAL,'Peru');
INSERT INTO PAIS(IDPAIS,NOMBREPAIS) VALUES (SEQ_PAIS_IDPAIS.NEXTVAL,'Panama');
