INSERT INTO PERSONA(IDPERSONA,NOMBRE,APELLIDO,GENERO,IDCIUDAD,IDPAIS,IDREGION) VALUES(1018485092,'Santiago','Collazos Barrera','M',1,1,1);
INSERT INTO PERSONA(IDPERSONA,NOMBRE,APELLIDO,GENERO,IDCIUDAD,IDPAIS,IDREGION) VALUES(1005855865,'Alvaro','Abril Olis','M',5,1,1);
INSERT INTO PERSONA(IDPERSONA,NOMBRE,APELLIDO,GENERO,IDCIUDAD,IDPAIS,IDREGION) VALUES(1016091072,'Johan Sebastian','Bonilla Plata','M',1,1,1);
INSERT INTO PERSONA(IDPERSONA,NOMBRE,APELLIDO,GENERO,IDCIUDAD,IDPAIS,IDREGION) VALUES(1023944061,'Pablo Andres','Cubillos Arias','M',1,1,1);
INSERT INTO PERSONA(IDPERSONA,NOMBRE,APELLIDO,GENERO,IDCIUDAD,IDPAIS,IDREGION) VALUES(1018492522,'Juan Andres','Rojas Alvarez','M',9,1,1);