INSERT INTO REGION(IDPAIS,IDREGION,NOMBREREGION) VALUES(1,SEQ_REGION_IDREGION.NEXTVAL,'Andina');
INSERT INTO REGION(IDPAIS,IDREGION,NOMBREREGION) VALUES(1,SEQ_REGION_IDREGION.NEXTVAL,'Pacifica');
INSERT INTO REGION(IDPAIS,IDREGION,NOMBREREGION) VALUES(1,SEQ_REGION_IDREGION.NEXTVAL,'Caribe');
INSERT INTO REGION(IDPAIS,IDREGION,NOMBREREGION) VALUES(1,SEQ_REGION_IDREGION.NEXTVAL,'Llanos Orientales');
INSERT INTO REGION(IDPAIS,IDREGION,NOMBREREGION) VALUES(1,SEQ_REGION_IDREGION.NEXTVAL,'Amazonia');
