INSERT INTO STOCK (IDSTOCK,IDPAIS,IDREGION,DIRECCIONSTOCK) VALUES (SEQ_STOCK_IDSTOCK.NEXTVAL,1,1,'Calle falsa numero 123');
INSERT INTO STOCK (IDSTOCK,IDPAIS,IDREGION,DIRECCIONSTOCK) VALUES (SEQ_STOCK_IDSTOCK.NEXTVAL,1,2,'Calle falsa numero 123');
INSERT INTO STOCK (IDSTOCK,IDPAIS,IDREGION,DIRECCIONSTOCK) VALUES (SEQ_STOCK_IDSTOCK.NEXTVAL,1,3,'Calle falsa numero 123');
INSERT INTO STOCK (IDSTOCK,IDPAIS,IDREGION,DIRECCIONSTOCK) VALUES (SEQ_STOCK_IDSTOCK.NEXTVAL,1,4,'Calle falsa numero 123');
INSERT INTO STOCK (IDSTOCK,IDPAIS,IDREGION,DIRECCIONSTOCK) VALUES (SEQ_STOCK_IDSTOCK.NEXTVAL,1,5,'Calle falsa numero 123');