/*Subcategorias para Nutricion*/
INSERT INTO SUBCATEGORIA (IDSUBCATEGORIA,NOMBRESUBCATEGORIA,IDCATEGORIA) VALUES (SEQ_SUBCRIA_IDSUBCRIA.NEXTVAL,'Proteinas',1);
INSERT INTO SUBCATEGORIA (IDSUBCATEGORIA,NOMBRESUBCATEGORIA,IDCATEGORIA) VALUES (SEQ_SUBCRIA_IDSUBCRIA.NEXTVAL,'Quemadores',1);
INSERT INTO SUBCATEGORIA (IDSUBCATEGORIA,NOMBRESUBCATEGORIA,IDCATEGORIA) VALUES (SEQ_SUBCRIA_IDSUBCRIA.NEXTVAL,'Pre-Entrenos',1);
INSERT INTO SUBCATEGORIA (IDSUBCATEGORIA,NOMBRESUBCATEGORIA,IDCATEGORIA) VALUES (SEQ_SUBCRIA_IDSUBCRIA.NEXTVAL,'Ganadores',1);
INSERT INTO SUBCATEGORIA (IDSUBCATEGORIA,NOMBRESUBCATEGORIA,IDCATEGORIA) VALUES (SEQ_SUBCRIA_IDSUBCRIA.NEXTVAL,'Aminohacidos',1);
/*Subcategorias para Belleza*/
INSERT INTO SUBCATEGORIA (IDSUBCATEGORIA,NOMBRESUBCATEGORIA,IDCATEGORIA) VALUES (SEQ_SUBCRIA_IDSUBCRIA.NEXTVAL,'Maquillaje de Labios',2);
INSERT INTO SUBCATEGORIA (IDSUBCATEGORIA,NOMBRESUBCATEGORIA,IDCATEGORIA) VALUES (SEQ_SUBCRIA_IDSUBCRIA.NEXTVAL,'Maquillaje de Rostro',2);
INSERT INTO SUBCATEGORIA (IDSUBCATEGORIA,NOMBRESUBCATEGORIA,IDCATEGORIA) VALUES (SEQ_SUBCRIA_IDSUBCRIA.NEXTVAL,'Maquillaje de Uñas',2);
INSERT INTO SUBCATEGORIA (IDSUBCATEGORIA,NOMBRESUBCATEGORIA,IDCATEGORIA) VALUES (SEQ_SUBCRIA_IDSUBCRIA.NEXTVAL,'Maquillaje de Ojos',2);
/*Subcategorias para Hogar*/
INSERT INTO SUBCATEGORIA (IDSUBCATEGORIA,NOMBRESUBCATEGORIA,IDCATEGORIA) VALUES (SEQ_SUBCRIA_IDSUBCRIA.NEXTVAL,'Aseo de Baño',3);
INSERT INTO SUBCATEGORIA (IDSUBCATEGORIA,NOMBRESUBCATEGORIA,IDCATEGORIA) VALUES (SEQ_SUBCRIA_IDSUBCRIA.NEXTVAL,'Aseo de la Cocina',3);
INSERT INTO SUBCATEGORIA (IDSUBCATEGORIA,NOMBRESUBCATEGORIA,IDCATEGORIA) VALUES (SEQ_SUBCRIA_IDSUBCRIA.NEXTVAL,'Ambientadores',3);
INSERT INTO SUBCATEGORIA (IDSUBCATEGORIA,NOMBRESUBCATEGORIA,IDCATEGORIA) VALUES (SEQ_SUBCRIA_IDSUBCRIA.NEXTVAL,'Cuidado de la Ropa',3);
/*Subcategorias para Cuidado personal*/
INSERT INTO SUBCATEGORIA (IDSUBCATEGORIA,NOMBRESUBCATEGORIA,IDCATEGORIA) VALUES (SEQ_SUBCRIA_IDSUBCRIA.NEXTVAL,'Cuidado Femenino',4);
INSERT INTO SUBCATEGORIA (IDSUBCATEGORIA,NOMBRESUBCATEGORIA,IDCATEGORIA) VALUES (SEQ_SUBCRIA_IDSUBCRIA.NEXTVAL,'Cuidado Masculino',4);
INSERT INTO SUBCATEGORIA (IDSUBCATEGORIA,NOMBRESUBCATEGORIA,IDCATEGORIA) VALUES (SEQ_SUBCRIA_IDSUBCRIA.NEXTVAL,'Cuidado Capilar',4);
INSERT INTO SUBCATEGORIA (IDSUBCATEGORIA,NOMBRESUBCATEGORIA,IDCATEGORIA) VALUES (SEQ_SUBCRIA_IDSUBCRIA.NEXTVAL,'Cuidado Corpolar',4);
INSERT INTO SUBCATEGORIA (IDSUBCATEGORIA,NOMBRESUBCATEGORIA,IDCATEGORIA) VALUES (SEQ_SUBCRIA_IDSUBCRIA.NEXTVAL,'Cuidado Facial',4);
INSERT INTO SUBCATEGORIA (IDSUBCATEGORIA,NOMBRESUBCATEGORIA,IDCATEGORIA) VALUES (SEQ_SUBCRIA_IDSUBCRIA.NEXTVAL,'Proteccion Solar y Repelentes',4);

