/*Subcategorias para Nutricion*/
INSERT INTO SUBCATEGORIA (IDSUBCATEGORIA,NOMBRESUBCATEGORIA) VALUES (SEQ_SUBCRIA_IDSUBCRIA.NEXTVAL,'Proteinas');
INSERT INTO SUBCATEGORIA (IDSUBCATEGORIA,NOMBRESUBCATEGORIA) VALUES (SEQ_SUBCRIA_IDSUBCRIA.NEXTVAL,'Quemadores');
INSERT INTO SUBCATEGORIA (IDSUBCATEGORIA,NOMBRESUBCATEGORIA) VALUES (SEQ_SUBCRIA_IDSUBCRIA.NEXTVAL,'Pre-Entrenos');
INSERT INTO SUBCATEGORIA (IDSUBCATEGORIA,NOMBRESUBCATEGORIA) VALUES (SEQ_SUBCRIA_IDSUBCRIA.NEXTVAL,'Ganadores');
INSERT INTO SUBCATEGORIA (IDSUBCATEGORIA,NOMBRESUBCATEGORIA) VALUES (SEQ_SUBCRIA_IDSUBCRIA.NEXTVAL,'Aminohacidos');
/*Subcategorias para Belleza*/
INSERT INTO SUBCATEGORIA (IDSUBCATEGORIA,NOMBRESUBCATEGORIA) VALUES (SEQ_SUBCRIA_IDSUBCRIA.NEXTVAL,'Maquillaje de Labios');
INSERT INTO SUBCATEGORIA (IDSUBCATEGORIA,NOMBRESUBCATEGORIA) VALUES (SEQ_SUBCRIA_IDSUBCRIA.NEXTVAL,'Maquillaje de Rostro');
INSERT INTO SUBCATEGORIA (IDSUBCATEGORIA,NOMBRESUBCATEGORIA) VALUES (SEQ_SUBCRIA_IDSUBCRIA.NEXTVAL,'Maquillaje de Uñas');
INSERT INTO SUBCATEGORIA (IDSUBCATEGORIA,NOMBRESUBCATEGORIA) VALUES (SEQ_SUBCRIA_IDSUBCRIA.NEXTVAL,'Maquillaje de Ojos');
/*Subcategorias para Hogar*/
INSERT INTO SUBCATEGORIA (IDSUBCATEGORIA,NOMBRESUBCATEGORIA) VALUES (SEQ_SUBCRIA_IDSUBCRIA.NEXTVAL,'Aseo de Baño');
INSERT INTO SUBCATEGORIA (IDSUBCATEGORIA,NOMBRESUBCATEGORIA) VALUES (SEQ_SUBCRIA_IDSUBCRIA.NEXTVAL,'Aseo de la Cocina');
INSERT INTO SUBCATEGORIA (IDSUBCATEGORIA,NOMBRESUBCATEGORIA) VALUES (SEQ_SUBCRIA_IDSUBCRIA.NEXTVAL,'Ambientadores');
INSERT INTO SUBCATEGORIA (IDSUBCATEGORIA,NOMBRESUBCATEGORIA) VALUES (SEQ_SUBCRIA_IDSUBCRIA.NEXTVAL,'Cuidado de la Ropa');
/*Subcategorias para Cuidado personal*/
INSERT INTO SUBCATEGORIA (IDSUBCATEGORIA,NOMBRESUBCATEGORIA) VALUES (SEQ_SUBCRIA_IDSUBCRIA.NEXTVAL,'Cuidado Femenino');
INSERT INTO SUBCATEGORIA (IDSUBCATEGORIA,NOMBRESUBCATEGORIA) VALUES (SEQ_SUBCRIA_IDSUBCRIA.NEXTVAL,'Cuidado Masculino');
INSERT INTO SUBCATEGORIA (IDSUBCATEGORIA,NOMBRESUBCATEGORIA) VALUES (SEQ_SUBCRIA_IDSUBCRIA.NEXTVAL,'Cuidado Capilar');
INSERT INTO SUBCATEGORIA (IDSUBCATEGORIA,NOMBRESUBCATEGORIA) VALUES (SEQ_SUBCRIA_IDSUBCRIA.NEXTVAL,'Cuidado Corpolar');
INSERT INTO SUBCATEGORIA (IDSUBCATEGORIA,NOMBRESUBCATEGORIA) VALUES (SEQ_SUBCRIA_IDSUBCRIA.NEXTVAL,'Cuidado Facial');
INSERT INTO SUBCATEGORIA (IDSUBCATEGORIA,NOMBRESUBCATEGORIA) VALUES (SEQ_SUBCRIA_IDSUBCRIA.NEXTVAL,'Proteccion Solar y Repelentes');

