INSERT INTO TARJETA(IDTARJETA,NOMBRETARJETA) VALUES (SEQ_TARJETA_IDTARJETA.NEXTVAL,'Master Card');
INSERT INTO TARJETA(IDTARJETA,NOMBRETARJETA) VALUES (SEQ_TARJETA_IDTARJETA.NEXTVAL,'Visa');
INSERT INTO TARJETA(IDTARJETA,NOMBRETARJETA) VALUES (SEQ_TARJETA_IDTARJETA.NEXTVAL,'American Express');
INSERT INTO TARJETA(IDTARJETA,NOMBRETARJETA) VALUES (SEQ_TARJETA_IDTARJETA.NEXTVAL,'Dinners Club');
