INSERT INTO TARJETA(IDTARJETA,NOMBRETARJETA) VALUES (SEQ_TARJETA_IDTARJETA.NEXTVAL,'');
INSERT INTO TARJETA(IDTARJETA,NOMBRETARJETA) VALUES (SEQ_TARJETA_IDTARJETA.NEXTVAL,'');
INSERT INTO TARJETA(IDTARJETA,NOMBRETARJETA) VALUES (SEQ_TARJETA_IDTARJETA.NEXTVAL,'');
INSERT INTO TARJETA(IDTARJETA,NOMBRETARJETA) VALUES (SEQ_TARJETA_IDTARJETA.NEXTVAL,'');
INSERT INTO TARJETA(IDTARJETA,NOMBRETARJETA) VALUES (SEQ_TARJETA_IDTARJETA.NEXTVAL,'');