INSERT INTO TIPOCONTACTO (IDTIPOCONTACTO,NOMBRETIPOCONTACTO) VALUES (SEQ_TIPOCTO_IDTIPOCTO.NEXTVAL,'Telefono');
INSERT INTO TIPOCONTACTO (IDTIPOCONTACTO,NOMBRETIPOCONTACTO) VALUES (SEQ_TIPOCTO_IDTIPOCTO.NEXTVAL,'Celular');
INSERT INTO TIPOCONTACTO (IDTIPOCONTACTO,NOMBRETIPOCONTACTO) VALUES (SEQ_TIPOCTO_IDTIPOCTO.NEXTVAL,'Correo Electronico');