INSERT INTO TIPOCONTACTO (IDTIPOCONTACTO,NOMBRETIPOCONTACTO) VALUES (SEQ_TIPOCONTACTO_ID.NEXTVAL,'Telefono');
INSERT INTO TIPOCONTACTO (IDTIPOCONTACTO,NOMBRETIPOCONTACTO) VALUES (SEQ_TIPOCONTACTO_ID.NEXTVAL,'Celular');
INSERT INTO TIPOCONTACTO (IDTIPOCONTACTO,NOMBRETIPOCONTACTO) VALUES (SEQ_TIPOCONTACTO_ID.NEXTVAL,'Correo Electronico');